// <auto-generated />
using System;
using ApiControleFinanceiro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiControleFinanceiro.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220210191700_AjustandoCategoria02")]
    partial class AjustandoCategoria02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiControleFinanceiro.Entities.CategoriaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idcategoria")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("ApiControleFinanceiro.Entities.LancamentoEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("idlancamento")
                        .HasColumnType("bigint");

                    b.Property<string>("Comentario")
                        .HasColumnName("comentario")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Data")
                        .HasColumnName("data")
                        .HasColumnType("date");

                    b.Property<double>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("lancamento");
                });

            modelBuilder.Entity("ApiControleFinanceiro.Entities.SubcategoriaEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("idsubcategoria")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("subcategoria");
                });

            modelBuilder.Entity("ApiControleFinanceiro.Entities.LancamentoEntity", b =>
                {
                    b.HasOne("ApiControleFinanceiro.Entities.SubcategoriaEntity", "SubcategoriaEntity")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiControleFinanceiro.Entities.SubcategoriaEntity", b =>
                {
                    b.HasOne("ApiControleFinanceiro.Entities.CategoriaEntity", "CategoriaEntity")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
